[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-lc++_shared"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-lc++_shared"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-lc++_shared"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-lc++_shared"]